### PR TITLE
Update WORKSPACE to point to material-foundation/xctestrunner.

### PR DESCRIPTION
**Pull request by jverkoey**
This enables us to run `bazel test` on this repo for pre-iOS 12.2 devices when building with Xcode 11.

https://github.com/material-foundation/material-testing-ios/issues/8 filed to track pointing back to google/xctestrunner.

Tested manually by running:

```
bazel test //... --apple_platform_type=ios
```

This is part of https://github.com/material-components/material-components-ios/issues/9363

### CODE REVIEW

**Comment by fluxminds** [comment]
I am fine with pointing it temporarily to your repo, though we have https://github.com/material-foundation/xctestrunner under material-foundation used for this purpose .

**Comment by jverkoey** [comment]
Ah! Let's use the foundation repo then.

**Comment by jverkoey** [comment]
Patch release made to https://github.com/material-foundation/xctestrunner/releases/tag/0.2.10-patch

**Comment by jverkoey** [comment]
Updated to point to foundation.

**Review by fluxminds — APPROVED** [review]
Thanks! Please update the PR title.

**Pull request merged**
